// LYNK 3D Solutions — shop product catalog.
// Prices are inclusive of VAT and shipping (baked-in, no extra shipping fee).
// Edit this file to tweak prices, add products, or change images.

export const PRODUCTS = [
    {
        id: 'aera-bathroom-organizer',
        name: 'AERA Bathroom Organizer',
        subtitle: 'Stijlvolle badkamerorganizer voor dagelijkse essentials',
        price: 29.95,
        image: 'img/product-organizer.png',
        colors: ['Wit', 'Zwart', 'Lichtgrijs'],
        material: 'PETG',
        description: 'Stevige badkamer-organizer voor zeep, tandenborstels en toiletartikelen. Geprint in waterbestendig PETG.',
    },
    {
        id: 'ancient-skull-pen-holder',
        name: 'Ancient Skull Pen Holder',
        subtitle: 'Gotische pennenhouder voor bureau of werkplek',
        price: 22.95,
        image: 'img/project-skull.png',
        colors: ['Zwart', 'Goud', 'Brons', 'Wit'],
        material: 'PLA',
        description: 'Gedetailleerde pennenhouder in skull-design. Perfect accent voor je bureau.',
    },
    {
        id: 'puffa-desk-organizer',
        name: 'Puffa Desk Organizer',
        subtitle: 'Modulair bureau-organizer voor al je spullen',
        price: 24.95,
        image: 'img/project-puffa.png',
        colors: ['Zwart', 'Wit', 'Blauw', 'Groen'],
        material: 'PLA',
        description: 'Modulair opbergsysteem voor pennen, kabels en kleine accessoires. Combineerbaar.',
    },
    {
        id: 'mario-toilet-holder',
        name: 'Mario Mystery Box Toilet Holder',
        subtitle: 'WC-rolhouder in iconisch Mario design',
        price: 26.95,
        image: 'img/project-mario.png',
        colors: ['Geel', 'Rood', 'Groen', 'Blauw'],
        material: 'PLA',
        description: 'Speelse WC-rolhouder als Super Mario mystery box. Houdt 2 extra rollen vast.',
    },
    {
        id: 'milwaukee-airpod-case',
        name: 'Milwaukee AirPod Pro Case',
        subtitle: 'Robuuste AirPods case in Milwaukee-stijl',
        price: 18.95,
        image: 'img/project-milwaukee.png',
        colors: ['Rood', 'Zwart'],
        material: 'TPU',
        description: 'Schokbestendige AirPods Pro case in herkenbare Milwaukee rood-zwart kleurstelling. Flexibel TPU.',
    },
    {
        id: 'embercore-fire-kit',
        name: 'EmberCore Survival Fire Kit',
        subtitle: 'Tactical firestarter organizer voor outdoor',
        price: 19.95,
        image: 'img/project-embercore.png',
        colors: ['Zwart', 'Olijfgroen', 'Coyote Tan'],
        material: 'PETG',
        description: 'Compacte firestarter-behuizing voor tinder, flint en staal. Water- en UV-bestendig PETG.',
    },
    {
        id: 'modern-key-holder',
        name: 'Modern Key Holder & Planter',
        subtitle: 'Sleutelbakje met geïntegreerde plantenschaal',
        price: 17.95,
        image: 'img/project-keyholder.png',
        colors: ['Wit', 'Zwart', 'Lichtgrijs', 'Crème'],
        material: 'PLA',
        description: 'Elegante entree-bakje voor sleutels, met schaaltje voor een kleine plant of succulent.',
    },
    {
        id: 'norflake-tealight',
        name: 'NORFLAKE Tealight Holder',
        subtitle: 'Scandinavisch geometrisch theelicht',
        price: 16.95,
        image: 'img/project-norflake.png',
        colors: ['Wit', 'Zwart', 'Lichtgrijs'],
        material: 'PLA',
        description: 'Sneeuwvlok-geïnspireerd theelicht met fijne geometrie. Set van 1 inclusief theelicht.',
    },
    {
        id: 'handwrap-roller',
        name: 'Handwrap Roller',
        subtitle: 'Handwrap oproller voor boks-/MMA-training',
        price: 19.95,
        image: 'img/project-handwrap.png',
        colors: ['Zwart', 'Rood', 'Blauw'],
        material: 'PETG',
        description: 'Ergonomische roller voor het opbergen van handwraps. Past standaardmaat handwraps.',
    },
    {
        id: 'dewalt-battery-holder',
        name: 'DeWalt Battery Holder',
        subtitle: 'Wandhouder voor DeWalt 18V / 20V accu\'s',
        price: 17.95,
        image: 'img/product-batteryholder.png',
        colors: ['Geel', 'Zwart'],
        material: 'PETG',
        description: 'Stevige wandmontage voor 3 DeWalt 18V/20V MAX accu\'s. Inclusief schroeven.',
    },
    {
        id: 'lynk-keychain',
        name: 'LYNK Custom Keychain',
        subtitle: 'Gepersonaliseerde sleutelhanger met jouw tekst',
        price: 14.95,
        image: 'img/product-keychain.png',
        colors: ['Zwart', 'Wit', 'Rood', 'Blauw', 'Groen', 'Geel'],
        material: 'PLA',
        description: 'Sleutelhanger met je eigen tekst (maximaal 14 tekens). Vermeld de tekst bij opmerkingen.',
        hasCustomText: true,
    },
];

export function findProduct(id) {
    return PRODUCTS.find(p => p.id === id) || null;
}
